# Generated by Django 2.2.4 on 2019-09-09 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0003_auto_20190830_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignee', to=settings.AUTH_USER_MODEL)),
                ('assignor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignor', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_job', to='job.Job')),
            ],
        ),
    ]
