# Generated by Django 2.2.4 on 2019-09-13 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeslot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
