# Generated by Django 2.2.4 on 2019-09-15 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0002_timeslot_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='owner',
            new_name='creator',
        ),
    ]
