# Generated by Django 2.2.4 on 2019-09-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0003_auto_20190915_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='end',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='start',
        ),
    ]
