# Generated by Django 2.2.4 on 2019-09-27 01:51

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0005_timeslot_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='duration',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(unique=True),
        ),
    ]
