# Generated by Django 2.2.4 on 2019-09-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0006_auto_20190926_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='duration',
            new_name='period',
        ),
    ]
