# Generated by Django 2.2.4 on 2019-08-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='admin status'),
        ),
    ]
