# Generated by Django 2.2.4 on 2019-09-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190830_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mode',
            field=models.CharField(blank=True, max_length=10, verbose_name='mode'),
        ),
    ]
