# Generated by Django 2.2.4 on 2019-09-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0002_timeslot_owner'),
        ('user', '0004_user_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timesheet',
            field=models.ManyToManyField(to='timeslot.TimeSlot'),
        ),
    ]
