# Generated by Django 2.2.4 on 2019-08-30 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='amount',
            new_name='price',
        ),
    ]
