# Generated by Django 2.2.4 on 2019-08-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20190830_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='status',
            new_name='job_status',
        ),
        migrations.AddField(
            model_name='job',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
