# Generated by Django 2.2.4 on 2019-09-27 07:17

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20190915_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='end',
        ),
        migrations.RemoveField(
            model_name='job',
            name='start',
        ),
        migrations.AddField(
            model_name='job',
            name='duration',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
