# Generated by Django 2.2.4 on 2019-09-28 13:49

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20190927_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='recess',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
