# Generated by Django 2.2.4 on 2019-09-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_recess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
